"""ok

Revision ID: 53d9b1e43c15
Revises: 
Create Date: 2019-10-29 21:49:15.929789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53d9b1e43c15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=7), nullable=True),
    sa.Column('display_name', sa.String(length=15), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_option_code'), 'search_option', ['code'], unique=False)
    op.create_index(op.f('ix_search_option_display_name'), 'search_option', ['display_name'], unique=False)
    op.create_index(op.f('ix_search_option_id'), 'search_option', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_option_id'), table_name='search_option')
    op.drop_index(op.f('ix_search_option_display_name'), table_name='search_option')
    op.drop_index(op.f('ix_search_option_code'), table_name='search_option')
    op.drop_table('search_option')
    # ### end Alembic commands ###
