"""more field added

Revision ID: 3d6449325048
Revises: daf935c7b1c0
Create Date: 2019-09-25 14:51:12.125131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d6449325048'
down_revision = 'daf935c7b1c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acno', sa.Integer(), nullable=True),
    sa.Column('unit_held', sa.Integer(), nullable=True),
    sa.Column('right_due', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('company', sa.String(length=140), nullable=True),
    sa.Column('right_date', sa.DateTime(), nullable=True),
    sa.Column('right_applied', sa.Integer(), nullable=True),
    sa.Column('additional_right_applied', sa.Integer(), nullable=True),
    sa.Column('additional_apply', sa.Integer(), nullable=True),
    sa.Column('additional_price', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('holder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holder'], ['share_holder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_right_acno'), 'right', ['acno'], unique=True)
    op.create_index(op.f('ix_right_id'), 'right', ['id'], unique=True)
    op.create_index(op.f('ix_right_timestamp'), 'right', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_right_timestamp'), table_name='right')
    op.drop_index(op.f('ix_right_id'), table_name='right')
    op.drop_index(op.f('ix_right_acno'), table_name='right')
    op.drop_table('right')
    # ### end Alembic commands ###
