"""first field added

Revision ID: daf935c7b1c0
Revises: 
Create Date: 2019-09-25 13:32:38.654721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'daf935c7b1c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('investor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.Integer(), nullable=True),
    sa.Column('acno', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sn')
    )
    op.create_index(op.f('ix_investor_acno'), 'investor', ['acno'], unique=True)
    op.create_index(op.f('ix_investor_id'), 'investor', ['id'], unique=True)
    op.create_table('share_holder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sn', sa.Integer(), nullable=True),
    sa.Column('acno', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('bvn', sa.Integer(), nullable=True),
    sa.Column('chn', sa.Integer(), nullable=True),
    sa.Column('agent_member_code', sa.String(length=140), nullable=True),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('cscs_account_no', sa.Integer(), nullable=True),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sn')
    )
    op.create_index(op.f('ix_share_holder_acno'), 'share_holder', ['acno'], unique=True)
    op.create_index(op.f('ix_share_holder_bvn'), 'share_holder', ['bvn'], unique=False)
    op.create_index(op.f('ix_share_holder_chn'), 'share_holder', ['chn'], unique=False)
    op.create_index(op.f('ix_share_holder_cscs_account_no'), 'share_holder', ['cscs_account_no'], unique=False)
    op.create_index(op.f('ix_share_holder_id'), 'share_holder', ['id'], unique=True)
    op.create_index(op.f('ix_share_holder_timestamp'), 'share_holder', ['timestamp'], unique=False)
    op.create_table('right',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acno', sa.Integer(), nullable=True),
    sa.Column('right_date', sa.Integer(), nullable=True),
    sa.Column('right_applied', sa.Integer(), nullable=True),
    sa.Column('additional_right_applied', sa.Integer(), nullable=True),
    sa.Column('unit_held', sa.Integer(), nullable=True),
    sa.Column('right_due', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('additional_apply', sa.Integer(), nullable=True),
    sa.Column('additional_price', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('holder', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['holder'], ['share_holder.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_right_acno'), 'right', ['acno'], unique=True)
    op.create_index(op.f('ix_right_id'), 'right', ['id'], unique=True)
    op.create_index(op.f('ix_right_timestamp'), 'right', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_right_timestamp'), table_name='right')
    op.drop_index(op.f('ix_right_id'), table_name='right')
    op.drop_index(op.f('ix_right_acno'), table_name='right')
    op.drop_table('right')
    op.drop_index(op.f('ix_share_holder_timestamp'), table_name='share_holder')
    op.drop_index(op.f('ix_share_holder_id'), table_name='share_holder')
    op.drop_index(op.f('ix_share_holder_cscs_account_no'), table_name='share_holder')
    op.drop_index(op.f('ix_share_holder_chn'), table_name='share_holder')
    op.drop_index(op.f('ix_share_holder_bvn'), table_name='share_holder')
    op.drop_index(op.f('ix_share_holder_acno'), table_name='share_holder')
    op.drop_table('share_holder')
    op.drop_index(op.f('ix_investor_id'), table_name='investor')
    op.drop_index(op.f('ix_investor_acno'), table_name='investor')
    op.drop_table('investor')
    # ### end Alembic commands ###
